site_name: BCBS Internship Overview

theme:
  name: material

markdown_extensions:
  - attr_list
  - md_in_html

nav:
- Home: index.md
- Projects: docs/sidebar/projects.md
- Software: docs/sidebar/software.md
- Presentations: docs/sidebar/presentations.md